peopledoc/septentrion

- README.md
> it doesn't do much at the moment
> Readme first draft.

- README.md
> Fix few typos in README file

- README.md
We don't need a consensus from everyone, so I guess the first or second approval may as well merge.
> Update README with precisions

- README.md
- tests/README.md
Do we agree on the methodology ? If so, let's write tests :)
> Initial documentation regarding the writing of tests

- tests/unit/test_init.py
- tests/unit/test_settings.py
- west/__init__.py
- west/settings.py
> More unit testing

- septentrion/__init__.py
- septentrion/cli.py
- septentrion/core.py
- septentrion/db.py
- septentrion/files.py
- septentrion/migrate.py
- septentrion/runner.py
- septentrion/settings.py
- septentrion/style.py
- septentrion/utils.py
- setup.cfg
- tests/integration/test_cli.py
- tests/unit/test_core.py
- tests/unit/test_files.py
- tests/unit/test_runner.py
- tests/unit/test_style.py
- tests/unit/test_utils.py
Fixes #28
Also changes the rule that says "no multiple imports on the same line
While going through all the code, I'm definitely convinced a few refactors would simplify a lot of things. The modelisation was subpar, and I say this as one of the main contributors of this lib. Amazing how one or two years gives you perspectives on coding habits...
> Fixes #28 Type annotations

- .github/CODEOWNERS
To his request ping @samuelhamard
> Add @samuelhamard

- README.rst
> A realistic stance in the readme

- README.rst
Just two minor changes to the main README file.
> Minor changes to README.rst

- release
Release script was broken. Here's to fix it.
(next step will be to switch to setup.py reading git describe I guess)
> Fix release script

- .github/CODEOWNERS
> Add @nadege as codeowner

- septentrion/__init__.py
- septentrion/lib.py
- septentrion/migration.py
- tests/unit/test_lib.py
Cf. https://people-doc.atlassian.net/browse/PY-32
a bit more is needed in the lib to make it work in django-north
> Add features to library

- README.rst
The smallest PR of the world ;-)
> Remove double space

- README.rst
Missing install instructions in readme
> Readme install instructions

- CONTRIBUTING.rst
- docker-compose.yml
Cf. no ticket again :(
It isn't really needed, but this way, the dev env is on par with other envs for PeopleDoc projects.
> Dev env: Add now mandatory password, set DB name

- docs/howto/advanced-options.rst
- docs/howto/configure.rst
- docs/howto/troubleshoot.rst
- docs/quickstart.rst
- septentrion/lib.py
- septentrion/migration.py
- tests/acceptance/test_cli.py
- tests/integration/test_db.py
- tests/unit/test_core.py
> Fix linting 87

- setup.cfg
I've also added spaces around `=` to stay consistent in the file.
> Setup: Fix URL to GitHub actions

- .github/workflows/ci.yml
- .github/workflows/publish.yml
> Fix CI python version

- setup.py
> Create setup.py to make dependabot happy

- poetry.lock
- pyproject.toml
> Add missing package dunamai

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- poetry.lock
- pyproject.toml
- scripts/bootstrap
> Syntax problem for pyproject.toml

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- poetry.lock
- pyproject.toml
- scripts/bootstrap
> Extra is psycopg2_binary and not psycopg2-binary

- README.rst
- poetry.lock
- pyproject.toml
> Require python 3.7+

- pyproject.toml
> Switch author to the Python community
