peopledoc/septentrion

septentrion/cli.py, septentrion/db.py
libpq uses a lot of environment variables [1] in order to build its
connection parameters.
The usage of these variables was documented but did not work.
Here we remove the default value from Septentrion: if the values are not
defined then psucopg2/libpq will look at its own environment variables.
The default values for psotgresql settings are now the ones from
psycopg2/libpq.
[1] https://www.postgresql.org/docs/10/libpq-envars.html
=> Permit libpq env variable usage

septentrion/db.py, septentrion/exceptions.py, septentrion/files.py, septentrion/utils.py, septentrion/versions.py, setup.cfg, tests/unit/test_version.py, tox.ini
No ticket
This allow to stop using `distutils.StrictVersion` implementation.
=> Replace StrictVersion to custom version

septentrion/runner.py
=> Python2 is not supported anymore, removing artifact

.github/CODEOWNERS
Add @CorBott as Code Owner for documentation, after she verbally agreed
=> Add Corinne as Code Owner for documentation

septentrion/cli.py
=> Fix typos in CLI help text

septentrion/files.py
This PR makes the `iter_dirs` and `iter_files` functions yield their items in alphabetical order.
The `tests/integration/test_files.py::test_iter_files` test didn't pass for me because of that.
=> Make iter_dirs and iter_files yield items in alphabetical order

README.rst, docs/howto/advanced-options.rst, docs/howto/configure.rst, docs/howto/file_naming.rst, docs/howto/troubleshoot.rst, docs/quickstart.rst
This is a first draft concerning the quick start guide in documentation. 
I have some questions (as "comments") in the rst. I'm struggling a bit with the level of details we want to provide here (minimal I guess, but I'm not familiar enough with SQL migration to know how much is needed). 
Comments welcome :) 
Stuff remaining to do:
=> Improving the quick start documentation

tests/unit/test_core.py, tests/unit/test_db.py
Cf. #29 but there is still work to do
=> Add some tests for db and core modules

septentrion/versions.py, tests/acceptance/test_cli.py, tests/unit/test_version.py
=> Fix version display in CLI

septentrion/__init__.py, septentrion/lib.py, tests/unit/test_lib.py
Add access to is_schema_initialized and build_migration_plan functions
I'm working on using septentrion in https://github.com/peopledoc/django-north
and I realized it needs those 2 features to check for unapplied migrations or uniitialized schema in its `runserver` command.
Cf. #60  and PY-32
=> PY-32 Extend septentrion lib module

septentrion/cli.py, septentrion/configuration.py, tests/acceptance/test_cli.py, tests/conftest.py, tests/unit/test_configuration.py
Closes #59 
- Fix loading of configuration when no file is available
- refactor load_config: click integration on one side, septentrion logic on the other side. This lets us unit test the logic much more easily.
- Default path is now internally a list of pathlib.Path, instead of str. Thanks to this, we can show full paths in logs, which should make things easier
=> Fix loading of configuration when no file is available (#59)

septentrion/db.py, tests/unit/test_db.py
Cf. no ticket
I haven't tested explicitely to find when the behaviour changed, but with `psycopg2==2.7.7`, explicit import of `psycopg2.errors` is required
=> Explicitly import psycopg2.errors for old psycopg2 versions

docs/quickstart.rst, requirements.txt, setup.cfg, tests/README.md, tox.ini
Cf. no ticket
It's actually problematic that septentrion depends on psycopg2 OR psycopg2-binary, because this means downstream projects can't choose anymore whether they want to use one or the other. We should be removing the dependency altogether and document the need to independently install *a* psycopg2 over 2.8.0, but this fills me with sadness.
Any suggestion ?
Edit: added 2 extras. And a lot of sorrow. At least, now it's solved; you decide whether you want `septentrion[psycopg2]` or `septentrion[psycopg2-binary]`
=> psycopg2 is required at 2.8.0 minimum

septentrion/runner.py, tests/conftest.py
Cf. no ticket
Septentrion is currently broken: password can only be passed via PGPASSWORD, the septentrion password option is not considered (because `--password {password}` is not a valid CLI flag)
(ping @k4nar)
=> Pass psql configuration by environment

septentrion/configuration.py, septentrion/core.py, septentrion/db.py, septentrion/lib.py, tests/integration/test_db.py, tests/unit/test_configuration.py
Cf. no ticket
- Lib: make target_version and schema_version Version objects
Before this change, schema_version was taken as a string, and comparison with Version objects failed.
- Write date in applied_at column
This is not the nicest thing because there should be a default here, but django-north will need to seriously step up its game before septentrion can rely on the DB default, sadly.
=> Fix versions

septentrion/core.py, septentrion/migration.py, septentrion/utils.py, tests/unit/test_core.py
Cf. #32 
With this PR, migrations older than the schema are not considered. If no schema is explicitely configured (even if one is used, because the latest schema is automatically used), then all migrations are considered.
Is it the right thing to do, or should I disregard all migrations older than the schema event when schema is not explicitely provided ?
Missing tests (& doc but the Septentrion doc is... Not ready)
=> Disregard migrations older than the schema

septentrion/lib.py, tests/unit/test_lib.py
No ticket
We recently changed the signature of build_migration_plan and we missed a spot.
We're on a schedule, so I'm fixing the existing thest, but I'm not ensuring that next time we have the problem, the tests will fail. I'm leaving this for a subsequent PR.
=> Lib: fix build_migration_plan

septentrion/runner.py, tests/integration/test_runner.py
This avoids suprocess.run to fail ambiguously due to non-string values inherited from configuration
(like postgresql' port number). 
Cf. #83.
=> Ensure env-vars are handled as strings

septentrion/cli.py, tests/acceptance/test_cli.py, tests/test_data/config_file.ini, tests/unit/test_configuration.py
Cf. #90 
New test without the fix:
```
$ pytest tests/acceptance/test_cli.py::test_configuration_file_from_cli
...
/home/tbcvl/Documents/dev/septentrion/septentrion/cli.py:37: in load_config
ctx.default_map = configuration.load_configuration_files(value)
/home/tbcvl/Documents/dev/septentrion/septentrion/configuration.py:195: in load_configuration_files
return parse_configuration_file(file_contents)
/home/tbcvl/Documents/dev/septentrion/septentrion/configuration.py:84: in parse_configuration_file
parser.read_string(content)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = …
```
=> #90 fix CLI call with --config-file option

septentrion/utils.py, tests/unit/test_core.py, tests/unit/test_utils.py
Closes #106 
I've validated that the new test:
- Fails if run before the patch
- Passes if fun after the patch
Ping @samuelhamard @matacoder
=> Fix build_migration_plan which ommitted the first version

.github/workflows/publish.yml
Fixes the publish workflow which runs twice, one of which will fail.
=> Publish workflow should just run on tag push

septentrion/lib.py, tests/unit/test_lib.py
=> Fix call to build_migration_plan (unexpected keyword 'schema_version')

.github/workflows/publish.yml
=> Publish on new releases
